### ISSUE TITLE
Cannot install these manually

### ISSUE THREAD

**Issue by FaCetheMoon** [ac-custom-shaders-patch/acc-extension-config#18] opened 2019-05-22 14:42 UTC
After downloading this zip file and extract files to assetto corsa/extension/ everytime I start racing ,content manager still download and  install from the cloud and the download speed in China is terrible,which forced me to turn off automatic install option and racing without these extensions. Maybe you can just let users drap-and-drop these files to CM?

**Comment by RustyChest** [comment] 2019-06-25 07:01
The issue is already resolved in the same opening post, to install these configurations manually it's best to just handle updating manually or through a self-written script rather than through Content Manager to avoid breakage.

**Closed** 2019-06-26 18:16 UTC
