### ISSUE TITLE
Wipers are broken in OpenVR rendering mode

### ISSUE THREAD

**Issue by goddamn-is-this-available** [ac-custom-shaders-patch/acc-extension-config#155] opened 2021-12-22 19:07 UTC
While playing in OpenVR rendering mode car wipers are broken: in the right eye some vertices of a wiper mesh are dragged out and distort it, while left eye is rendered fine.

Reproduced in Valve Index on CSP 0.1.75
Does not reproduce on CSP 0.1.74

**Comment by Blumlaut** [comment] 2022-01-19 16:22
some more information as i just discovered there's an issue for this already, i personally **cannot** reproduce this issue with the following configuration:
```
Reverb G2
Intel i7 7700k
RTX 3060 12GB with 511.23 Drivers
CSP 0.1.76-preview137
Sol 2.2.2 b2
Natural Mod ppFilter
```

Configuration:
https://acstuff.ru/s/rF1xpB
https://acstuff.ru/s/YrInlt

SteamVR is set to 100% res scale, Motion Smoothing is disabled. Advanced Supersample Filtering disabled.

for other people this seemingly happens with both OVR and Oculus Renderer with cars that employ the CSP Wipers in their Configs, AE86, BMW Z4, Lambo Countach etc etc.

I also tried swapping CSP presets with affected users and could not trigger it.

**Comment by Vannipo** [comment] 2022-02-13 11:57
It concerns OculusVR, too.
And single screen.
Here a single screen screenshot of the Porsche GT3 Cup
![20210724173632_1](https://user-images.githubusercontent.com/76270473/153751969-dfc65f60-5728-415f-8cb0-b8447251fe72.jpg)
.

**Comment by Vannipo** [comment] 2022-02-13 19:40
Still in 0.1.76

**Comment by Vannipo** [comment] 2022-02-23 10:19
Here a left eye screenshot
![20220223112448_1](https://user-images.githubusercontent.com/76270473/155300271-448eb2eb-66b8-45d2-813d-deb8bbfda8b6.jpg)
.

**Comment by Vannipo** [comment] 2022-02-23 10:34
KS Porsche GT3 Cup. CSP > 0.1.74.
Right eye shows exploded mesh. Wiper on left and right eye have different shapes.

For this Porsche, car config [ANIMATED_WIPER_...] does something strange with the wipers anyway. Wiper stuck in the windscreen. Even in single screen. Left eye represents single screen.

![20220223113352_1](https://user-images.githubusercontent.com/76270473/155302556-9dbabd09-d591-4962-97ee-0e0abe9a70ee.jpg)

**Comment by Vannipo** [comment] 2022-02-23 10:45
https://user-images.githubusercontent.com/76270473/155304190-2dbd1d9e-4713-46ad-9540-702a820f0b5c.mp4

**Comment by Blumlaut** [comment] 2022-02-28 23:40
reportedly still present as of 1.77

**Comment by Blumlaut** [comment] 2022-03-05 21:24
not sure if regression applies here, theres also a rumor going around that Post Processing OFF causes the issue to no longer appear, would be great if @goddamn-is-this-available @Vannipo and whoever is affected could try that, might help narrow it down

**Comment by Blumlaut** [comment] 2022-03-05 22:32
one more lead maybe? 2 people on Pascal series GPUs (1080 and 1080ti) tried it and both got the wiper bug, one person without any headset-specific firmware (running steamvr without an actual headset), another with a WMR Odyssey. I'm personally on a 3060 now, but DID get it back when i was running a 1070Ti, could this be hardware related?

**Comment by Trava715** [comment] 2022-03-05 22:34
![image](https://user-images.githubusercontent.com/43389722/156901954-812cb567-88f9-4505-9cb5-dab9ffb4e8dc.png)
 Confirmed fix with post processing off.

**Comment by Trava715** [comment] 2022-03-05 22:39
> one more lead maybe? 2 people on Pascal series GPUs (1080 and 1080ti) tried it and both got the wiper bug, one person without any headset-specific firmware (running steamvr without an actual headset), another with a WMR Odyssey. I'm personally on a 3060 now, but DID get it back when i was running a 1070Ti, could this be hardware related?

For posterity, OP has this issue on a 970.

**Comment by Blumlaut** [comment] 2022-03-05 23:59
after getting together some people on the CSP Discord, here are our metrics!
1x 900 series with bug
6x 1000 series with bug

3x 2000 series can't repro 
3x 3000 series can't repro

So this _does_ seem to be related to GPU Generation, drivers were almost exclusively 511.** so not driver version is not related.

**Comment by SkyKingRP** [comment] 2022-03-15 23:54
I am having the exact same issue, running a GTX 1070 in Oculus Rift rendering mode, with an Oculus Rift CV1.  I use OpenComposite instead of SteamVR, as it provides better frame rates.  This problem began with the Patreon versions of CSP 0.1.76, which introduced some kind of wiper feature.  If I downgrade to CSP 0.1.75 or earlier, the issue goes away (of course there is no rain then, so the wipers are pointless).  This issue only seems to occur with certain Kunos cars - only one mod car so far has been similarly affected, a Porsche 914-6.  These are the Kunos cars that have the issue so far:

BMW 1M
BMW 1M Stage 3
Ferrari 458 GT2
Lamborghini Countach
Lotus Elise SC
Lotus Evora GTE
Mazda Miata NA
Mazda Miata ND
Nissan 350Z Nismo
Porsche 911 GT3 Cup
Porsche 911 RSR 2017
Porsche 911 Turbo S

The rest of the Kunos cars and mod cars are fine.

**Comment by Trava715** [comment] 2022-03-16 03:25
I think sample size of 26 with a consistently reproducible pattern is enough to conclude that it's a hardware issue.
@gro-ove

**Comment by Vannipo** [comment] 2022-03-18 12:15
CSP 0.1.78p18
Now both eyes show the same deformed wiper
![20220318131149_1](https://user-images.githubusercontent.com/76270473/159001285-4c51f3bb-5ef1-4664-9a5e-85fd2888cdfc.jpg)

**Comment by Vannipo** [comment] 2022-03-18 12:38
https://user-images.githubusercontent.com/76270473/159004344-eef9bc3f-8257-4ed9-a32e-b52000053841.mp4

**Comment by Vannipo** [comment] 2022-03-26 15:45
Summarized:
It concerns everyone on GTX 9- and 10-series in VR.
On **CSP 0.1.78p18 both eyes** show the same deformed wiper.
On **CSP < 0.1.78p18 only the right eye** shows a deformed wiper. Left eye looks like single screen and correct.

**Comment by FedericoGutierrezS** [comment] 2022-04-07 04:36
Found a temporal fix, (quest 2, gtx1070) go into steamapps/assettocorsa/extension/config/cars/loaded, there you should see the car configs downloaded from csp's github, find the car you have problems with, make a copy of the ini file and add something to the original name, for example I copied bmw_m3_e30.ini and renamed the copy bmw_m3_e30_base.ini , then go into bmw_m3_e30.ini, erase everything, and write
[INCLUDE]
INCLUDE=common/bmw_m3_e30_base.ini
I don't know why, but that fixed it for me, and I have wiper anims and everything, If the car is not there, there should be an extension folder on the folder of the car itself in contents. I guess something weird happens when it reads directly from the file instead of including it...
(Wrote this everywhere for awareness, tried it with the porsche and it didnt work, I'll try more stuff)

**Comment by Trava715** [comment] 2022-06-08 18:38
Closing, #246 expands further on the issue.

**Closed by Trava715** 2022-06-08 18:38 UTC
Labels: bug, regression
