### ISSUE TITLE
`MATERIAL_ADJUSTMENT_...` isn't working without declaring `CONDITION` on 1.78p18

### ISSUE THREAD

**Issue by Marocco2** [ac-custom-shaders-patch/acc-extension-config#241] opened 2022-03-27 16:28 UTC
Apparently `MATERIAL_ADJUSTMENT_...` isn't functional on 1.78p18 if `CONDITION` is empty or not present. This is a serious bug as it will break many configs that don't use `SHADER_REPLACEMENT_...` for static changes.
Regression is unknown for previous builds

**Comment by Trava715** [comment] 2022-03-28 03:21
Works as intended in 1.77 public
![image](https://user-images.githubusercontent.com/43389722/160321014-701d40ba-ec81-4127-a2de-0ccc58945bab.png)

**Comment by Vannipo** [comment] 2022-03-28 18:45
Just did a quick test on "mugello.ini". This Material Adjustment worked so far. Or is it about Material Adjustments without ID?
![image](https://user-images.githubusercontent.com/76270473/160465570-6565b8f3-21e8-478f-9dee-c48fc5173841.png)
![image](https://user-images.githubusercontent.com/76270473/160465598-b703b4b1-fb98-4150-901e-d9410a342983.png)

**Comment by Vannipo** [comment] 2022-03-29 15:56
> Check ... ones

Sorry, what do you mean?

**Comment by Marocco2** [comment] 2022-03-29 16:30
Material Adjustments without ID

**Comment by Vannipo** [comment] 2022-03-29 18:05
> Material Adjustments without ID

Yeah, that I thought about, too.
Then I tried also with ID -> Worked in this case.

**Comment by Trava715** [comment] 2022-04-30 17:23
Closing as it cannot be reproduced and no one else reported it in almost a month.

**Closed by Trava715** 2022-04-30 17:23 UTC
Labels: bug, critical, review required, regression
