### ISSUE TITLE
[CSP WIPERS] Wiper animations broken on GTX9/10 series in single screen mode

### ISSUE THREAD

**Issue by Vannipo** [ac-custom-shaders-patch/acc-extension-config#246] opened 2022-03-31 09:20 UTC
Related to this issue:
https://github.com/ac-custom-shaders-patch/acc-extension-config/issues/155
it's now broken since CSP 0.1.78p18 even on single screen.

**Comment by Vannipo** [comment] 2022-03-31 13:55
ks_alfa_33_stradal
https://user-images.githubusercontent.com/76270473/161072170-c8928906-e2e6-4976-bef6-c27dc11afb53.mp4

**Comment by Vannipo** [comment] 2022-03-31 13:56
https://user-images.githubusercontent.com/76270473/161072271-b9d2b325-5e81-4146-9d24-ffae4603cab8.mp4

ks_alfa_33_stradale

**Comment by Vannipo** [comment] 2022-03-31 13:57
https://user-images.githubusercontent.com/76270473/161072536-c0612a14-c84f-4ced-a19e-090301a7f67f.mp4

ks_mazda_mx5_nd

**Comment by RustyChest** [comment] 2022-04-02 04:15
Seems like an understandable bug but how are we sure it's strictly tied to 9/10 series cards? 

What card do you have out of the 9/10 series?

Which driver are you using on your GPU?

Are these issues present with/without Sol/PURE?

Do these same issues exist with ExtraFX on/off? 

Have you tried deleting the car's config to ensure no one's defined specific wiper paths?

My educated guess here is that somehow, magically, the node/dummy for the wipers isn't being read by CSP properly nor is the scaling for that matter so the animation just goes straight to hell. 

But for future reference please keep in mind that you should try asking yourself questions that would help determine what has/hasn't worked and document _before_ submitting a bug

I'll look into this, though I don't seem to be affected by it just yet, perhaps it's temperamental?

**Comment by Trava715** [comment] 2022-04-02 05:11
@RustyChest https://github.com/ac-custom-shaders-patch/acc-extension-config/issues/155#issuecomment-1059855104

**Comment by Vannipo** [comment] 2022-04-02 18:09
@RustyChest 

> Seems like an understandable bug but how are we sure it's strictly tied to 9/10 series cards?
We know, cause we asked many people to repro the issue. Seems, it only affects users with GTX 9-/10- series

> What card do you have out of the 9/10 series?
GTX 1080ti

> Which driver are you using on your GPU?
Seems, driver version doesn't matter. Most users are on the latest 512.x, I am on 472.x

> Are these issues present with/without Sol/PURE?
Yes

> Do these same issues exist with ExtraFX on/off?
Yes

> Have you tried deleting the car's config to ensure no one's defined specific wiper paths?
No, but if I comment out the lines concerning ANIMATED WIPER, the used default KSANIM works

> My educated guess here is that somehow, magically, the node/dummy for the wipers isn't being read by CSP properly nor is the scaling for that matter so the animation just goes straight to hell.
I don't know
 
> But for future reference please keep in mind that you should try asking yourself questions that would help determine what has/hasn't worked and document _before_ submitting a bug
It's just a further step related to https://github.com/ac-custom-shaders-patch/acc-extension-config/issues/155.
**CSP versions < .78p18** && work in single screen, but the **right eye in VR** is affected. But since **.78p18** in VR both eyes are affected and even single screen mode. So, something changed between the last versions. I don't know what.
 
> I'll look into this, though I don't seem to be affected by it just yet, perhaps it's temperamental?
If you are not on a GTX 9-/10- you won't be able to reproduce. But hopefully someone/you is able to fix that in the near future, since there even exist videos on Youtube showing how to delete lines in car configs as a temporarily fix.

This is no new bug. It exists since version .75. Since CSP animated wipers are supported. But 1st in VR right eye, now even on single screen. This issue should be tagged as critical.

**Comment by Trava715** [comment] 2022-04-02 20:05
Critical is reserved for game breaking bugs. Having to put up with bad kunos animations until it's fixed is not one.

You can blame Ilja for pushing global updates that are enabled by default without testing them because it's not the first time he's done that and surely not the last.

**Comment by Vannipo** [comment] 2022-04-04 14:18
> Critical is reserved for game breaking bugs....

👍

**Comment by Vannipo** [comment] 2022-04-04 18:07
Still persists on 0.1.78p23. Just for info.

**Comment by FedericoGutierrezS** [comment] 2022-04-07 04:28
Found a temporal fix, (quest 2, gtx1070) go into steamapps/assettocorsa/extension/config/cars/loaded, there you should see the car configs downloaded from csp's github, find the car you have problems with, make a copy of the ini file and add something to the original name, for example I copied bmw_m3_e30.ini and renamed the copy bmw_m3_e30_base.ini , then go into bmw_m3_e30.ini, erase everything, and write 
[INCLUDE]
INCLUDE=common/bmw_m3_e30_base.ini
I don't know why, but that fixed it for me, and I have wiper anims and everything, If the car is not there, there should be an extension folder on the folder of the car itself in contents. I guess something weird happens when it reads directly from the file instead of including it...

**Comment by FedericoGutierrezS** [comment] 2022-04-07 06:35
Changing the [ANIMATED_WIPER...] seccion of the cup 2017 ini to this will make them kinda work, but they remove just a part of rain from the windshield, I've been 3 hours working on this now, so I'm going to sleep, but it would seem it's just a matter of configuring it right. I have no idea what I'm doing with these, but it's probably just a lack of time and interest in VR from Ilja's part I guess

[ANIMATED_WIPER_...]
MESHES = polymsh33, polymsh_detached23, polymsh29
UNDERLYING_SURFACE = GEO_Windows_SUB0, GEO_Windows_SUB1
ANIMATION_OFFSET=0.25
GROUP_0='polymsh33@A=*', 'polymsh_detached23@A=*', 'polymsh29@A=*'
GROUP_0_ANGLE_FROM=-60
GROUP_0_ANGLE_TO=60
GROUP_0_AXIS=0,1,0.5
GROUP_0_END=-0.0107, 1.2, 0.307
GROUP_0_PIVOT=-0.0033, 0.84, 1.09
GROUP_0_RUBBER_FROM = 0.007261, 1.026079, 0.636737
GROUP_0_RUBBER_OFFSET_AMOUNT = 0.0000001
GROUP_0_RUBBER_TO = 0, 1.1, 0.5

GROUP_0_LAGGING_BEHIND="polymsh33=1-3"
GROUP_0_LAGGING_BEHIND_AMOUNT=0.5
GROUP_0_LAGGING_BEHIND_PIVOT=0.6
GROUP_0_LAGGING_BEHIND_RANGE=0.5

GROUP_0_TURNING="polymsh33=1-3", "polymsh_detached23=1-3"
GROUP_0_TURNING_PIVOT=0.0075, 0.918, 0.904
GROUP_0_TURNING_AXIS=1, 0, 0.5
GROUP_0_TURNING_ANGLE_LUT=(|0=10|0.5=0|1=10|)
GROUP_0_TURNING_ANGLE_LUT_CUBIC=1

**Comment by chas1723** [comment] 2022-04-07 11:28
I have a 980ti with the latest drivers.  I can confirm every car that has csp wipers implemented that I have tried, shows this bug.  URD and Kunos are the ones I have tried.

**Comment by Vannipo** [comment] 2022-04-10 20:57
> Found a temporal fix

Yeah, the reason why that "fixes" it for you is

INCLUDE=**common**/bmw_m3_e30_base.ini

You are including a config, which doesn't exist in the subfolder **common**. That's why you just see a car ingame without a car config and you see the original Kunos wiper animation. 😂

**Comment by Vannipo** [comment] 2022-04-10 21:07
> lack of time and interest in VR

U really didn't get the point. Again. Like with your "temporal fix".
This thread isn't about VR only anymore. It concerns single screen since CSP versions above 0.1.78p1.

**Comment by Vannipo** [comment] 2022-04-10 21:27
> I've been 3 hours working on this now

Then it's easier (and faster) remaking the original wiper animation. Like I did already. At least this cleanes the complete windscreen. 😉

https://user-images.githubusercontent.com/76270473/162640556-78b38ad9-a2cb-49ef-8c9c-e419c62af5bf.mp4

**Comment by Vannipo** [comment] 2022-04-13 11:47
Heard it's fixed in CSP 0.1.78p25. Have no access, so I am not able to test...

**Comment by Vannipo** [comment] 2022-04-22 15:21
**FIXED on CSP 0.1.78p45**
Both, VR and Single screen. GTX 1080ti, Rift S.

Great work!

https://user-images.githubusercontent.com/76270473/164744774-c486f444-7b3c-4f4b-b248-7d2146654f15.mp4

**Comment by Trava715** [comment] 2022-06-08 18:38
Fixed in 1.78.

**Closed by Trava715** 2022-06-08 18:38 UTC
Labels: bug
