### ISSUE TITLE
[Proton/Linux] CSP versions 1.79 and 1.80-preview1 won't load ("Can't find INIReader::cache")

### ISSUE THREAD

**Issue by ChUrl** [ac-custom-shaders-patch/acc-extension-config#316] opened 2022-10-24 13:47 UTC
I am able to run AC with CSP version 1.79-preview5 (and previous versions) on Proton6.3-8.
Newer versions (1.79-full and 1.80-preview1) won't load with the following error:
![Screenshot_20221024_142943](https://user-images.githubusercontent.com/46786696/197527333-f3890047-6060-4384-be85-8680c38b3d15.png)

My installed AC version is the one specified in the error (1.16.4 64bit).
I'm a bit confused because these "INIReader::cache" mappings (in extension/config/data_alt_mapping.ini) didn't change between 1.79-preview5 and 1.80-preview1...

<details>
  <summary>CSP 1.80-preview1 log</summary>
  
  ```
 2022-10-24T13:15:06:721 [00384] | INFO  | Custom Shaders Patch 0.1.80-preview1 is up and running.
2022-10-24T13:15:06:721 [00384] | INFO  | Please avoid using this log file for anything or parsing it in any way. Next update might not print anything here at all.
2022-10-24T13:15:06:722 [00384] | INFO  | Time in race.ini: 43200, sun angle=-16
2022-10-24T13:15:06:722 [00384] | DEBUG | New shared archive: 'Z:\home\name\drive\SteamLibrary\steamapps\common\assettocorsa\extension\internal/lua.zip'
2022-10-24T13:15:06:722 [00384] | INFO  | Archive opened: 'Z:\home\name\drive\SteamLibrary\steamapps\common\assettocorsa\extension\internal/lua.zip'
2022-10-24T13:15:06:725 [00384] | INFO  | Extension `DXGI Tweaks` disabled
2022-10-24T13:15:06:725 [00384] | INFO  | Setting AC hooks…
2022-10-24T13:15:06:725 [00384] | INFO  | Target: acs
2022-10-24T13:15:07:165 [00384] | INFO  |   Target initialized
2022-10-24T13:15:21:683 [00384] | DEBUG | In total, 25486 different names and 35243 items were found; 59184 were skipped as useless
2022-10-24T13:15:21:684 [00384] | INFO  | Running with Wine
2022-10-24T13:15:21:684 [00384] | DEBUG | Alternative mapping: use different name `INIReader::useCache`: `?useCache@INIReader@@2_NA`, index=-1
2022-10-24T13:15:21:684 [00384] | DEBUG | Alternative mapping: use different name `INIReader::cache`: `?cache@INIReader@@1V?$map@V?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@V?$map@V?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@UINISection@@U?$less@V?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@@2@V?$allocator@U?$pair@$$CBV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@UINISection@@@std@@@2@@2@U?$less@V?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@@2@V?$allocator@U?$pair@$$CBV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@V?$map@V?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@UINISection@@U?$less@V?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@@2@V?$allocator@U?$pair@$$CBV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@UINISection@@@std@@@2@@2@@std@@@2@@std@@A`, index=-1
2022-10-24T13:15:21:685 [00384] | DEBUG | Alternative mapping: use different name `formCurrentOffset`: `?formCurrentOffset@@3Vvec2f@@A`, index=-1
2022-10-24T13:15:21:685 [00384] | DEBUG | Alternative mapping: use different name `videoSettings`: `?videoSettings@@3UKGLVideoSettings@@A`, index=-1
2022-10-24T13:15:21:685 [00384] | DEBUG | Alternative mapping: use different name `device`: `?device@@3PEAUID3D11Device@@EA`, index=-1
2022-10-24T13:15:21:685 [00384] | DEBUG | Alternative mapping: use different name `immediateContext`: `?immediateContext@@3PEAUID3D11DeviceContext@@EA`, index=-1
2022-10-24T13:15:21:685 [00384] | DEBUG | Alternative mapping: use different name `swapChain`: `?swapChain@@3PEAUIDXGISwapChain@@EA`, index=-1
2022-10-24T13:15:21:685 [00384] | DEBUG | Alternative mapping: use different name `currentLayout`: `?currentLayout@@3PEAUID3D11InputLayout@@EA`, index=-1
2022-10-24T13:15:21:685 [00384] | DEBUG | Alternative mapping: use different name `videoSettings`: `?videoSettings@@3UKGLVideoSettings@@A`, index=-1
2022-10-24T13:15:21:686 [00384] | DEBUG | Alternative mapping: use different name `CarLodManager::lodDistDivisor`: `?lodDistDivisor@CarLodManager@@2MA`, index=-1
2022-10-24T13:15:21:686 [00384] | DEBUG | Alternative mapping: use different name `RaceManager::carsToBeLoaded`: `?carsToBeLoaded@RaceManager@@2HA`, index=-1
2022-10-24T13:15:21:687 [00384] | DEBUG | Alternative mapping: use different name `blendStates`: `?blendStates@@3PAPEAUID3D11BlendState@@A`, index=-1
2022-10-24T13:15:21:687 [00384] | DEBUG | Alternative mapping: use different name `cullStates`: `?cullStates@@3PAPEAUID3D11RasterizerState@@A`, index=-1
2022-10-24T13:15:21:687 [00384] | DEBUG | Alternative mapping: use different name `depthStates`: `?depthStates@@3PAPEAUID3D11DepthStencilState@@A`, index=-1
2022-10-24T13:15:21:687 [00384] | DEBUG | Alternative mapping: use different name `activeRenderTargetView`: `?activeRenderTargetView@@3PEAUID3D11RenderTargetView@@EA`, index=-1
2022-10-24T13:15:21:687 [00384] | DEBUG | Alternative mapping: use different name `activeDepthStencilView`: `?activeDepthStencilView@@3PEAUID3D11DepthStencilView@@EA`, index=-1
2022-10-24T13:15:21:687 [00384] | DEBUG | Alternative mapping: use different name `frameInformation`: `?frameInformation@@3V?$vector@UFrameInformation@@V?$allocator@UFrameInformation@@@std@@@std@@A`, index=-1
2022-10-24T13:15:21:687 [00384] | DEBUG | Alternative mapping: use different name `replayLeaderboards`: `?replayLeaderboards@@3V?$vector@V?$vector@ULeaderboardEntry@@V?$allocator@ULeaderboardEntry@@@std@@@std@@V?$allocator@V?$vector@ULeaderboardEntry@@V?$allocator@ULeaderboardEntry@@@std@@@std@@@2@@std@@A`, index=-1
2022-10-24T13:15:21:687 [00384] | DEBUG | Alternative mapping: use different name `ReplayRecorder::recordIntervalMS`: `?recordIntervalMS@GhostCarRecorder@@2NB`, index=-1
2022-10-24T13:15:21:687 [00384] | DEBUG | Alternative mapping: use different name `pHMD`: `?pHMD@@3PEAVIVRSystem@vr@@EA`, index=-1
2022-10-24T13:15:21:688 [00384] | INFO  |   Hooks prepared
2022-10-24T13:15:21:688 [00384] | INFO  | Time to find things: 14521.98 ms
2022-10-24T13:15:21:688 [00384] | ERROR | Failed to initialize
2022-10-24T13:15:24:554 [00384] | DEBUG | Closing shared archive: 'Z:\home\name\drive\SteamLibrary\steamapps\common\assettocorsa\extension\internal/lua.zip'

  ```
</details>

<details>
  <summary>CSP 1.79-preview5 log</summary>

```
2022-10-24T13:28:04:090 [00392] | INFO  | Custom Shaders Patch 0.1.79-preview5 is up and running.
2022-10-24T13:28:04:090 [00392] | INFO  | Please avoid using this log file for anything or parsing it in any way. Next update might not print anything here at all.
2022-10-24T13:28:04:091 [00392] | INFO  | Time in race.ini: 43200, sun angle=-16
2022-10-24T13:28:04:091 [00392] | DEBUG | New shared archive: 'Z:\home\name\drive\SteamLibrary\steamapps\common\assettocorsa\extension\internal/lua.zip'
2022-10-24T13:28:04:091 [00392] | INFO  | Archive opened: 'Z:\home\name\drive\SteamLibrary\steamapps\common\assettocorsa\extension\internal/lua.zip'
2022-10-24T13:28:04:093 [00392] | INFO  | Extension `DXGI Tweaks` disabled
2022-10-24T13:28:04:093 [00392] | INFO  | Setting AC hooks…
2022-10-24T13:28:04:563 [00392] | INFO  | Target: acs
2022-10-24T13:28:19:210 [00392] | DEBUG | In total, 32851 different names and 46519 items were found; 47908 were skipped as useless
2022-10-24T13:28:19:211 [00392] | INFO  | Running with Wine
2022-10-24T13:28:19:211 [00392] | DEBUG | Alternative mapping: use different name `INIReader::useCache`: `?useCache@INIReader@@2_NA`
2022-10-24T13:28:19:211 [00392] | DEBUG | Alternative mapping: use different name `INIReader::cache`: `?cache@INIReader@@1V?$map@V?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@V?$map@V?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@UINISection@@U?$less@V?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@@2@V?$allocator@U?$pair@$$CBV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@UINISection@@@std@@@2@@2@U?$less@V?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@@2@V?$allocator@U?$pair@$$CBV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@V?$map@V?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@UINISection@@U?$less@V?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@@2@V?$allocator@U?$pair@$$CBV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@UINISection@@@std@@@2@@2@@std@@@2@@std@@A`
2022-10-24T13:28:19:212 [00392] | DEBUG | Alternative mapping: use different name `formCurrentOffset`: `?formCurrentOffset@@3Vvec2f@@A`
2022-10-24T13:28:19:213 [00392] | DEBUG | Alternative mapping: use different name `videoSettings`: `?videoSettings@@3UKGLVideoSettings@@A`
2022-10-24T13:28:19:213 [00392] | DEBUG | Alternative mapping: use different name `device`: `?device@@3PEAUID3D11Device@@EA`
2022-10-24T13:28:19:213 [00392] | DEBUG | Alternative mapping: use different name `immediateContext`: `?immediateContext@@3PEAUID3D11DeviceContext@@EA`
2022-10-24T13:28:19:213 [00392] | DEBUG | Alternative mapping: use different name `swapChain`: `?swapChain@@3PEAUIDXGISwapChain@@EA`
2022-10-24T13:28:19:213 [00392] | DEBUG | Alternative mapping: use different name `currentLayout`: `?currentLayout@@3PEAUID3D11InputLayout@@EA`
2022-10-24T13:28:19:213 [00392] | DEBUG | Alternative mapping: use different name `videoSettings`: `?videoSettings@@3UKGLVideoSettings@@A`
2022-10-24T13:28:19:213 [00392] | DEBUG | Alternative mapping: use different name `CarLodManager::lodDistDivisor`: `?lodDistDivisor@CarLodManager@@2MA`
2022-10-24T13:28:19:213 [00392] | DEBUG | Alternative mapping: use different name `RaceManager::carsToBeLoaded`: `?carsToBeLoaded@RaceManager@@2HA`
2022-10-24T13:28:19:214 [00392] | DEBUG | Alternative mapping: use different name `blendStates`: `?blendStates@@3PAPEAUID3D11BlendState@@A`
2022-10-24T13:28:19:214 [00392] | DEBUG | Alternative mapping: use different name `cullStates`: `?cullStates@@3PAPEAUID3D11RasterizerState@@A`
2022-10-24T13:28:19:214 [00392] | DEBUG | Alternative mapping: use different name `depthStates`: `?depthStates@@3PAPEAUID3D11DepthStencilState@@A`
2022-10-24T13:28:19:214 [00392] | DEBUG | Alternative mapping: use different name `activeRenderTargetView`: `?activeRenderTargetView@@3PEAUID3D11RenderTargetView@@EA`
2022-10-24T13:28:19:214 [00392] | DEBUG | Alternative mapping: use different name `activeDepthStencilView`: `?activeDepthStencilView@@3PEAUID3D11DepthStencilView@@EA`
2022-10-24T13:28:19:214 [00392] | DEBUG | Alternative mapping: use different name `frameInformation`: `?frameInformation@@3V?$vector@UFrameInformation@@V?$allocator@UFrameInformation@@@std@@@std@@A`
2022-10-24T13:28:19:214 [00392] | DEBUG | Alternative mapping: use different name `replayLeaderboards`: `?replayLeaderboards@@3V?$vector@V?$vector@ULeaderboardEntry@@V?$allocator@ULeaderboardEntry@@@std@@@std@@V?$allocator@V?$vector@ULeaderboardEntry@@V?$allocator@ULeaderboardEntry@@@std@@@std@@@2@@std@@A`
2022-10-24T13:28:19:214 [00392] | DEBUG | Alternative mapping: use different name `ReplayRecorder::recordIntervalMS`: `?recordIntervalMS@GhostCarRecorder@@2NB`
2022-10-24T13:28:19:215 [00392] | DEBUG | Alternative mapping: use different name `pHMD`: `?pHMD@@3PEAVIVRSystem@vr@@EA`
2022-10-24T13:28:19:215 [00392] | INFO  | Time to find things: 14650.37 ms
2022-10-24T13:28:19:228 [00392] | INFO  | All 1784 functions were found successfully
```
</details>

**Comment by zezic** [comment] 2022-11-05 15:51
Same for me:
![Screenshot_20221104_192136](https://user-images.githubusercontent.com/1945127/200128466-0a1774df-1ce8-4e53-8281-cd491456f2a5.png)
[custom_shaders_patch.log](https://github.com/ac-custom-shaders-patch/acc-extension-config/files/9944179/custom_shaders_patch.log)

**Comment by OSuKaRuXD** [comment] 2022-11-14 18:49
hope is helping, but i found that, somehow the issue is related to ~/assetto corsa/extension/config/data_alt_mapping.ini maybe?

Maybe is in the dwrite.dll itself. The issue is that the mod cannot find a INIReader::cache equivalent in the Wine/Proton database. That's as far i found out.

`INIReader::cache/0x0='?cache@INIReader@@1V?$map@V?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@V?$map@V?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@UINISection@@U?$less@V?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@@2@V?$allocator@U?$pair@$$CBV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@UINISection@@@std@@@2@@2@U?$less@V?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@@2@V?$allocator@U?$pair@$$CBV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@V?$map@V?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@UINISection@@U?$less@V?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@@2@V?$allocator@U?$pair@$$CBV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@UINISection@@@std@@@2@@2@@std@@@2@@std@@A'
`
The funny thing is <1.79 works perfectly fine and found it without issue with that exact line.

**Comment by zezic** [comment] 2022-11-14 19:02
@OSuKaRuXD Don't worry! The bug will be fixed with the next release of CSP (1.80).

**Comment by TonySSS100** [comment] 2022-12-03 22:30
Only problem for me is when I switch to Proton 6.3-8, the PFX gets screwed and gives me NET missing message, so I'm personally forced to use 5.0-10 until I find another version which works. I also tried to just replace dwrite file from a previous CSP and it will work, but won't make all features work properly so I was forced to replace extensions folder as well.

Lastly, sorry if unrelated to CSP but CM also has a lot of its own problems on Linux such as showroom crashing, a fatal error while scrolling in car selection with also crash, no possibility of easly changing track skins yet among many others I presume. I'm concerned already on how long it may take for Ilja to realize CM isn't either compatible on Linux yet and find a way to make it work properly, slowly but eventually...

**Comment by ChUrl** [comment] 2022-12-25 13:09
It seems like the issue is fixed with CSP 0.1.80-preview108 :)

**Closed** 2022-12-25 19:11 UTC
Labels: help wanted, review required

**Comment by sevmonster** [comment] 2023-05-20 06:47
I also had this problem, even on the latest preview. After a fresh install, I installed CSP from CM, downgraded to 1.78, then upgraded to 1.80-preview218. Not entirely sure if the fresh install or that is what helped :)

You will also want to run `protontricks 244210 corefonts` as the newer CM versions utilize various Windows fonts that are not shipped with WINE or Proton/Proton-GE.

**Comment by LisyFOX** [comment] 2025-02-03 14:17
I had the same problem on any CSP >=1.76 with even more mappings couldn't be found, but I found an easy solution working even on the latest CSP.

All you've got to do is to completely remove `[NAMES_WINE]` config block in `assettocorsa/extension/config/data_alt_mapping.ini`

[lines_to_remove.txt](https://github.com/user-attachments/files/18643377/lines_to_remove.txt)

**Comment by BlackShadeOSS** [comment] 2025-06-16 14:09
> I had the same problem on any CSP >=1.76 with even more mappings couldn't be found, but I found an easy solution working even on the latest CSP.
> 
> All you've got to do is to completely remove `[NAMES_WINE]` config block in `assettocorsa/extension/config/data_alt_mapping.ini`
> 
> [lines_to_remove.txt](https://github.com/user-attachments/files/18643377/lines_to_remove.txt)

this fix work thanks
